version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - misspell
    - revive
    - unconvert
  settings:
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: range
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
      - third_party
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party
      - third_party$
      - builtin$
      - examples$
